export default [
  { name: "LED", diagram: `{"type": "wokwi-led","id": "led1","top": 50,"left": 50,"attrs": { "color": "red", "value": "" } }`, component: "wokwi-led"},
  { name: "PushButton", diagram: `{"type": "wokwi-pushbutton","id": "btn1","top": 50,"left": 50,  "attrs": { "color": "green" }}`, component: "wokwi-pushbutton"},
  { name: "Resistor", diagram: `{"type": "wokwi-resistor","id": "r1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-resistor"},
  { name: "Slide Switch", diagram: `{"type": "wokwi-slide-switch","id": "sw1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-slide-switch"},
  { name: "Membrane Keypad", diagram: `{"type": "wokwi-membrane-keypad","id": "keypad1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-membrane-keypad"},
  { name: "Logic Analyzer", diagram: `{"type": "wokwi-logic-analyzer","id": "logic1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-logic-analyzer"},
  { name: "MAX7219 Matrix", diagram: `{"type": "wokwi-max7219-matrix","id": "matrix1","top": 50,"left": 50,"attrs": { "chain": "4" }}`, component: "wokwi-max7219-matrix"},
  { name: "Neopixel", diagram: `{"type": "wokwi-neopixel","id": "rgb1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-neopixel"},
  { name: "LED Ring", diagram: `{"type": "wokwi-led-ring","id": "ring1","top": 50,"left": 50,"attrs": { "pixels": "16" }}`, component: "wokwi-led-ring"},
  { name: "Neopixel Meter", diagram: `{"type": "wokwi-neopixel-meter","id": "ring2","top": 50,"left": 50,"attrs": { "pixels": "16" }}`, component: "wokwi-neopixel-meter"},
  { name: "Buzzer", diagram: `{"type": "wokwi-buzzer","id": "bz1","top": 50,"left": 50,"attrs": { "volume": "0.1" }}`, component: "wokwi-buzzer"},
  { name: "DHT22", diagram: `{"type": "wokwi-dht22","id": "dht1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-dht22"},
  { name: "Potentiometer", diagram: `{"type": "wokwi-potentiometer","id": "pot1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-potentiometer"},
  { name: "Slide Potentiometer", diagram: `{"type": "wokwi-slide-potentiometer","id": "pot2","top": 50,"left": 50,"attrs": { "travelLength": "30" }}`, component: "wokwi-slide-potentiometer"},
  { name: "LCD 1602", diagram: `{"type": "wokwi-lcd1602","id": "lcd1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-lcd1602"},
  { name: "LCD 2004", diagram: `{"type": "wokwi-lcd2004","id": "lcd2","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-lcd2004"},
  { name: "Servo", diagram: `{"type": "wokwi-servo","id": "servo1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-servo"},
  { name: "Rotary Dialer", diagram: `{"type": "wokwi-rotary-dialer","id": "dialer1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-rotary-dialer"},
  { name: "SSD 1306", diagram: `{"type": "wokwi-ssd1306","id": "oled1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-ssd1306"},
  { name: "ILI 9341", diagram: `{"type": "wokwi-ili9341","id": "lcd3","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-ili9341"},
  { name: "DS1307", diagram: `{"type": "wokwi-ds1307","id": "rtc1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-ds1307"},
  { name: "HC SR04", diagram: `{"type": "wokwi-hc-sr04","id": "ultrasonic1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-hc-sr04"},
  { name: "RGB LED", diagram: `{"type": "wokwi-rgb-led","id": "rgb2","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-rgb-led"},
  { name: "7Segment", diagram: `{"type": "wokwi-7segment","id": "sevseg2","top": 50,"left": 50,"attrs": { "digits": "4" }}`, component: "wokwi-7segment"},
  { name: "LED Bar Graph", diagram: `{"type": "wokwi-led-bar-graph","id": "bargraph1","top": 50,"left": 50,"attrs": { "color": "lime" }}`, component: "wokwi-led-bar-graph"},
  { name: "Analog Joystick", diagram: `{"type": "wokwi-analog-joystick","id": "joystick1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-analog-joystick"},
  { name: "IR Receiver", diagram: `{"type": "wokwi-ir-receiver","id": "ir1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-ir-receiver"},
  { name: "IR Remote", diagram: `{"type": "wokwi-ir-remote","id": "remote1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-ir-remote"},
  { name: "PIR Motion Sensor", diagram: `{"type": "wokwi-pir-motion-sensor","id": "pir1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-pir-motion-sensor"},
  { name: "NTC Temperature Sensor", diagram: `{"type": "wokwi-ntc-temperature-sensor","id": "ntc1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-ntc-temperature-sensor"},
  { name: "74hc595", diagram: `{"type": "wokwi-74hc595","id": "sr1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-74hc595"},
  { name: "74HC165", diagram: `{"type": "wokwi-74hc165","id": "sr2","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-74hc165"},
  { name: "NLSF595", diagram: `{"type": "wokwi-nlsf595","id": "sr3","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-nlsf595"},
  { name: "Photoresistor sensor", diagram: `{"type": "wokwi-photoresistor-sensor","id": "ldr1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-photoresistor-sensor"},
  { name: "KY 040", diagram: `{"type": "wokwi-ky-040","id": "encoder1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-ky-040"},
  { name: "MPU6050", diagram: `{"type": "wokwi-mpu6050","id": "imu1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-mpu6050"},
  { name: "MicroSD Card", diagram: `{"type": "wokwi-microsd-card","id": "sd1","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-microsd-card"},
  { name: "DIP Switch 8", diagram: `{"type": "wokwi-dip-switch-8","id": "sw2","top": 50,"left": 50,"attrs": {}}`, component: "wokwi-dip-switch-8"}
]